name: 'Build'
on:
  push:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-13, ubuntu-22.04, windows-2022]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Deploy Rust to CI
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Deploy frontend dependencies
        run: pnpm install
      - name: Compile software
        run: pnpm tauri build --ci
      - name: Upload the Linux packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-22.04'
        with:
          name: linux-packages
          path: src-tauri/target/release/bundle/appimage/*.AppImage
      - name: Upload the macOS packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'macos-13'
        with:
          name: macos-packages
          path: src-tauri/target/release/bundle/dmg/*.dmg
      - name: Upload the Windows packages
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-2022'
        with:
          name: windows-packages
          path: src-tauri/target/release/*.exe
